version: "3"

services:
  catalog_server:
    build: ./catalog_server
    ports:
      - "3000:3000"
    depends_on:
      - database

  order_server:
    build: ./order_server
    ports:
      - "3001:3001"

  database:
    image: "keinos/sqlite3" # Use a pre-built SQLite image or create your own
    volumes:
      - ./database # Mount the local SQLite directory into the container
