version: "3"

services:
  catalog_server:
    build: ./catalog_server
    ports:
      - "3000:3000"
    depends_on:
      - database

  catalog_server_replica1:
    build: ./catalog_server_replica1
    ports:
      - "4000:4000"
    depends_on:
      - database

  catalog_server_replica2:
    build: ./catalog_server_replica2
    ports:
      - "5000:5000"
    depends_on:
      - database

  order_server:
    build: ./order_server
    ports:
      - "3001:3001"

  order_server_replica1:
    build: ./order_server_replica1
    ports:
      - "4001:4001"

  order_server_replica2:
    build: ./order_server_replica2
    ports:
      - "5001:5001"

  database:
    image: "keinos/sqlite3" #this image for some reason doesn't work properly
    volumes:
      - ./database # Mount the local SQLite directory into the container
