version: "3"

services:
  catalog_server:
    build: ./catalog_server
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      PORT: 3000

  catalog_server_replica1:
    build: ./catalog_server_replica1
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      PORT: 4000

  catalog_server_replica2:
    build: ./catalog_server_replica2
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      PORT: 5000

  order_server:
    build: ./order_server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001

  order_server_replica1:
    build: ./order_server_replica1
    ports:
      - "4001:4001"
    environment:
      PORT: 4001

  order_server_replica2:
    build: ./order_server_replica2
    ports:
      - "5001:5001"
    environment:
      PORT: 5001

  database:
    image: "keinos/sqlite3"
    volumes:
      - ./database
